; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# Slow down upload speed to prevent serial corruption
upload_speed = 115200

# Board overrides for 16MB Flash and 8MB Octal PSRAM (N16R8 module with Quad/Dual flash)
board_build.flash_mode = dio
board_build.f_flash = 80000000L             # Uses bootloader_dio_80m.elf (precompiled)
board_build.arduino.memory_type = dio_opi   # DIO Flash + OPI PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags =
    -DARDUINO_BOARD_HAS_PSRAM
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/tzapu/WiFiManager.git
